# Generated by Django 5.0.7 on 2024-07-13 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_task_description_en_task_description_ru_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='creted_date',
            new_name='crated_date',
        ),
    ]
